export enum Labels {
  TITLE = "DreamDesign",
  TITLE1 = "Dream",
  TITLE2 = "Design",
  SIGN_IN = "Sign In",
  SIGN_UP = "Sign Up",
  RANDOMIZE_ALL = "Randomize all",
  UPLOAD_DESIGN = "Upload the design",
  APPLY = "Apply",
  CANCEL = "Cancel",
  STYLE = "Style",
  CATEGORY = "Category",
  SIZE = "Size",
  MATERIAL = "Material",
  COLOUR = "Colour",
  BUDGET = "Budget",
  BEDROOM = "Bedroom",
  LIVING_ROOM = "Living room",
  DINING_ROOM = "Dining room",
  STUDY_OFFICE = "Study/Office",
  KITCHEN = "Kitchen",
  PLACEHOLDER_LENGTH = "Length",
  PLACEHOLDER_WIDTH = "Width",
  PLACEHOLDER_HEIGHT = "Height",
  PLACEHOLDER_MIN = "Min",
  PLACEHOLDER_MAX = "Max",
}